version: '3.0'
services:
  redislima:
    image: redislabs/redismod
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    # ports:
    #   - '6379:6379'
    volumes:
      - redis_data_lima:/data
  lima:
    # image: lima-service
    image: wwlib/robokit:lima-service
    env_file:
      - lima-service.env
    ports:
      - '8084:8084'
      
volumes:
  redis_data_lima:
    external: false